### ISSUE TITLE
Fix handling of "... X is a Y created by ..."

### ISSUE THREAD

**Issue by sfelshin** [infolab-csail/whoami#109]
These types are bogus.  It looks like "created" somehow managed to end up as the object of "to be":
```
$ telnet <host> 8023
(get-types "D (programming language)")
("multi-paradigm created" "created" "programming language created"
 "system programming language created" "language created" "object-oriented" "imperative created")
```
When I [parse in displaCy](https://demos.explosion.ai/displacy/?text=The%20D%20programming%20language%20is%20an%20object-oriented%2C%20imperative%2C%20multi-paradigm%20system%20programming%20language%20created%20by%20Walter%20Bright%20of%20Digital%20Mars%20and%20released%20in%202001.&model=en_core_web_sm&cpu=1&cph=0), I get a dependencies `[is attr language]` and `[language acl created]`, which are reasonable. I don't get any dependency between `is` and `created`.

Is this a bug in whoami?  Or is it a bug in spaCy that has since been fixed, and we merely need to compute types in a new WikipediaBase backend?

**Comment by shu98** [comment]
@sfelshin  I tested and a couple of other examples in whoami and I think it is no longer a whoami/spaCy problem. Specifically, these are the types I get now from whoami

> ['multi-paradigm system programming language', 'system programming language', 'language', 'imperative language', 'object-oriented language', 'programming language']

In any case, I would check the WikipediaBase backend.
