### ISSUE TITLE
Address security alerts from GitHub

### ISSUE THREAD

**Issue by sfelshin** [infolab-csail/whoami#129]
https://github.com/infolab-csail/whoami/network/alerts

**Comment by sfelshin** [comment]
@hanryhu, #141 claims to have addressed this issue but didn't manage to close it. On purpose, or oversight (due to GitHub's touchy rules for closing issues using keywords?)?

**Comment by hanryhu** [comment]
Resolved by https://github.com/infolab-csail/whoami/pull/141.
