### ISSUE TITLE
Modify parsing of nationalities to increase precision

### ISSUE THREAD

**Issue by alvaromorales** [infolab-csail/whoami#3]
Nationality parsing needs to be improved (we're currently scanning the sentence for the first nationality word). Given:

> John is a student in the United States

whoami returns: `student, american`. Definitions should only be generated from the definition subtree.

**Comment by alvaromorales** [comment]
`NationalityTest.testNationalityInPP` tests for this:

```java
	public void testNationalityInPP() {
		String sentence = "Islam is a religion practiced in Afghanistan.";
		Set<String> definitions = DefinitionExtractor.extractDefinitionsFromStatement(sentence).getDefinitions();
		Set<String> expected = Sets.newHashSet("religion");
		assertEquals("Wrong definitions", expected, definitions);
	}
```

The test is ignored by the test runner. The `@Ignore` annotation needs to be removed after closing this issue.

**Comment by moldot** [comment]
Moving to new python whoami
