### ISSUE TITLE
Explore dependency parsers as an alternative to constituency parsers

### ISSUE THREAD

**Issue by alvaromorales** [infolab-csail/whoami#4]
We've had issues with the precision of constituency parsers. In addition, tree regex patterns are starting to get hacky and hard to maintain.

The output of a dependency parser looks promising for whoami. It might map nicely to START's t-expressions, making the integration easier.

Let's explore dependency parsers.

Sample output:

> John is an American actor and a student of computer science at MIT in Cambridge.

root ( ROOT-0 , actor-5 )
nsubj ( actor-5 , John-1 )
cop ( actor-5 , is-2 )
det ( actor-5 , an-3 )
amod ( actor-5 , American-4 )
cc ( actor-5 , and-6 )
det ( student-8 , a-7 )
conj:and ( actor-5 , student-8 )
case ( science-11 , of-9 )
compound ( science-11 , computer-10 )
nmod:of ( student-8 , science-11 )
case ( MIT-13 , at-12 )
nmod:at ( science-11 , MIT-13 )
case ( Cambridge-15 , in-14 )
nmod:in ( MIT-13 , Cambridge-15 )

**Comment by alvaromorales** [comment]
You should check out http://spacy.io

It apparently has a better parser than CoreNLP, and it's all in Python. If Spacy does what it's docs say, it would be a huge win.

**Comment by moldot** [comment]
Spacy seems promising, and python will probably be significantly less painful than Java. Are we using whoami mostly though HTTP interface (and thus we can switch languages safely)?

CoreNLP demo is currently down so I can't test it, but I'll do that when it's back up.

**Comment by alvaromorales** [comment]
Yes, we can switch languages safely. If whoami is in python, we can just import it as a library in projects like elasticstart. We wouldn't even need to have an HTTP server.

**Comment by moldot** [comment]
spaCy looks promising. Migrating to python.
