### ISSUE TITLE
Filter out incompatible or unrelated definitions

### ISSUE THREAD

**Issue by alvaromorales** [infolab-csail/whoami#43]
Consider the sentence: Alan Mathison Turing, OBE, FRS was a British pioneering computer scientist, mathematician, logician, cryptanalyst, philosopher, mathematical biologist, and marathon and ultra distance runner.

Whoami returns: scientist, [...] mathematician, [...] **marathon**, runner, ultra runner, distance runner, british

We should use some data source, e.g. Wordnet distance, to determine that person definitions like scientist or mathematician aren't "compatible" with marathon.

**Comment by moldot** [comment]
More example: 
Thayendanegea or Joseph Brant was a Mohawk military and political leader, based in present-day New York, who was closely associated with Great Britain during and after the American Revolution.
Joseph Brant is a military, Mohawk military, leader, political leader
