### ISSUE TITLE
Wrong definition: island

### ISSUE THREAD

**Issue by alvaromorales** [infolab-csail/whoami#44]
Consider the sentence: Canadian Forces Base Summerside was an air force base located in St. Eleanors, Prince Edward Island, Canada, now part of the city of Summerside.

(Article: CFB Summerside)

Island should not be a definition

**Comment by moldot** [comment]
This hapoens because 'island' is an apposition of 'base', and we treat apposition somewhat like conjunction. This needs to be further investigated.

**Comment by shu98** [comment]
I tested this and don't think it is an issue anymore.
