### ISSUE TITLE
Specify subject and its synonyms to help spaCy with parsing

### ISSUE THREAD

**Issue by alvaromorales** [infolab-csail/whoami#46]
Consider the following example:

Sentence: Born to Run is the third studio album by the American singer-songwriter Bruce Springsteen.
Article: Born to Run

We fail to extract definitions because spaCy parses run as a verb.

We can easily pass the subject of the sentence to whoami, and perhaps even its synonyms from Wikipedia. Before we parse with spaCy, we can make a fake noun out of the subject, e.g. `Born_to_Run`. 

This strategy seems to work -- I tested it using the spaCy web [demo](https://api.spacy.io/displacy/index.html).

**Comment by alvaromorales** [comment]
It seems like Spanish words confuse spaCy. This enhancement would also help us for the sentence: Voces a mi Alrededor is a 1993 album by Franco De Vita released on the Sony label.

**Comment by moldot** [comment]
Closed by #56
