### ISSUE TITLE
Get synonyms of wikipedia articles

### ISSUE THREAD

**Issue by moldot** [infolab-csail/whoami#54]
Following #46, whoami needs a list of synonyms of the article subjects in order to correctly recognize the subject and preprocess the sentence.

**Comment by moldot** [comment]
Mostly done. A remaining issue is checking with WikipediaBase if the article is about the person.

**Comment by moldot** [comment]
Unfortunately I can't remember why we need to check if the article is about a person. Do you remember this @alvaromorales?

**Comment by alvaromorales** [comment]
I can't remember either, unfortunately. That being said, I think it's out of scope for whoami to check for synonyms. The caller should be responsible for passing the correct subject. Whoami should not need to ask an external service like WikipediaBase for synonyms

To get definitions from Wikipedia, we'll need to pass in the first bolded phrase as the subject. For example, looking at Barack Obama's article:

> **Barack Hussein Obama II** (US Listeni/bəˈrɑːk huːˈseɪn oʊˈbɑːmə/;[3][4] born August 4, 1961) is an American politician serving as the 44th President of the United States, the first African American to hold the office.

The caller should specify "Barack Hussein Obama II" as the subject.

I guess we can close this issue?

**Comment by moldot** [comment]
It seems to be working fine (except for the known bugs). I don't see now why whoami need to go to WikipediaBase itself either. Let's close this.
