### ISSUE TITLE
Infinite loop in preprocess:replace_subject

### ISSUE THREAD

**Issue by alvaromorales** [infolab-csail/whoami#77]
I'm rebuilding wikithingsdb, and I noticed that whoami gets stuck with the following input:

```python
from whoami.query import get_assertion_definitions
get_assertion_definitions(u'is a manga series by Mine Yoshizaki.', subject=[u'e'])
```

This first sentence is incorrectly extracted from [Sgt. Frog](https://en.wikipedia.org/wiki/Sgt._Frog) because a template is used to rendered Japanese characters. Even with bad input, whoami shouldn't get stuck in an infinite loop.

**Comment by alvaromorales** [comment]
On my end, I'm trying to mitigate this issue by adding a fake subject (but I'm still running into the infinite loop bug):

```python
sentence = u'is a manga series by Mine Yoshizaki.'
names = [u'e']

if sentence.startswith('is a'):
    # some articles use templates to render foreign characters in the first
    # sentence of the article
    # see 'Sgt. Frog' for an example
    # this causes us to strip out the entire contents of the template
    # to mitigate this, we add a fake subject
    sentence = u'Subj ' + sentence
    names = [u'Subj']
```

Let me know if you prefer a different patch.

**Comment by moldot** [comment]
Oh no. This is because the dummy subject is 'subject_number_xxx", and substitution works by replacing the subject synonyms with the dummy subject until the subject synonyms are no longer found. Problem here is that 'e' is in 'subject_number_xxx", so it keeps replacing infinitely. Will fix now,
