### ISSUE TITLE
Working prototype with basic capabilities

### ISSUE THREAD

**Issue by moldot** [infolab-csail/whoami#8]
Create a minimal working prototype that exhibit how spaCy may be used, how accurate it is, and what are the limitations. Make sure that definition extraction works first, and future work may be on the output (t-expressions, lists of definitions, etc.)

**Comment by alvaromorales** [comment]
Great progress so far! For future reference, there's no need to reference issues from git commit messages ("`Issue: #8`"). Just create a [pull request](https://help.github.com/articles/using-pull-requests/) when you're done pushing commits to a branch, and reference the issue in the PR description. In this way, you only have to reference the issue once, and all commits in the PR refer to it.

For an example of a PR that uses this workflow, see https://github.com/infolab-csail/WikipediaBase/pull/74
