### ISSUE TITLE
Subject synonyms have a trailing space

### ISSUE THREAD

**Issue by pondpremt** [infolab-csail/whoami#87]
MainThread - DEBUG - .. whoami exception for: "The Long Beach Public Library is the public library of Long Beach, New York, serving the civic, cultural, educational and recreational needs of the community." ([u'**Long Beach Public Library '**, u'Long Beach Public Library (New York)', u'Long Beach Public Library'])

MainThread - DEBUG - .. whoami exception for: "John G. Montijo was an American aircraft engineer and instructor." ([u**'John G. Montijo '**, u'John G. Montijo'])

**Comment by moldot** [comment]
Can this be fixed in the caller of whoami?

**Comment by alvaromorales** [comment]
Yes, will fix in the caller.

(Sorry for the late reply -- I didn't see the notification for this issue)

**Comment by shu98** [comment]
Has this been fixed or can I take over?

**Comment by shu98** [comment]
Closed by #111
