### ISSUE TITLE
Remove non-noun definitions

### ISSUE THREAD

**Issue by pondpremt** [infolab-csail/whoami#90]
==> blue

Gene Deer is an American blues, rock, and country musician/singer/songwriter based out of Indianapolis, Indiana. [Gene Deer]
Gil Parris is an American Grammy-nominated rock, blues, jazz and pop guitarist. [Gil Parris]
Tanya Wright is an actress known for her starring on "Buddies" as Phyllis Brooks, as well as her recurring roles on "24" as Patty Brooks, "NYPD Blue" as Officer Maya Anderson, on "True Blood" as Deputy Kenya Jones, and as Crystal on the Netflix original series "Orange Is the New Black". [Tanya Wright]
Rick Bryant is a New Zealand blues and rock singer/songwriter. [Rick Bryant]
Calvin Leavy was an African American soul blues and electric blues singer and guitarist. [Calvin Leavy]
The West Coast blues is a type of blues influenced by jazz and jump blues, with strong piano-dominated sounds and jazzy guitar solos, which originated from Texas blues players who relocated to California in the 1940s. [West Coast blues]

==> red

The beetroot is the taproot portion of the beet plant, usually known in North America as the beet, also table beet, garden beet, or red or golden beet. [Beetroot]
In CRT or computer terminology, a triad is a group of three phosphor dots coloured red, green, and blue on the inside of the CRT display of a computer monitor or television set. [Triad (computers)]
Ulmus 'Coolshade' is an American hybrid cultivar cloned from a crossing of the Slippery, or Red, Elm "Ulmus rubra" and the Siberian Elm "Ulmus pumila" at the Sarcoxie Nurseries, Sarcoxie, Missouri, in 1946. [Ulmus 'Coolshade']
Upsdell red is a deep medium red, similar to Fire engine red. [Upsdell red]
Thorstein Eiriksson was the third and youngest son of Eiríkr the Red and brother of Leif Ericson. [Thorstein Eiriksson]

==> before

Daydreamin' is the only album released by R&amp;B group, Before Dark. [Daydreamin' (Before Dark album)]
Tired of Not Being Away from Here is the fifth studio album, and second LP, recorded by the indie rock band, Before Braille. [Tired of Not Being Away from Here]
"Crush" is a song by the Dave Matthews Band, released as the third single from their album "Before These Crowded Streets". [Crush (Dave Matthews Band song)]
"Friends" is a song by Danish singer-songwriter Aura Dione from her second studio album, "Before the Dinosaurs". [Friends (Aura Dione song)]
Kill the Messenger, Keep the Message is the sixth studio album, and third LP, recorded by the indie rock band, Before Braille. [Kill the Messenger, Keep the Message]
"Pig" is a Dave Matthews Band song from the album "Before These Crowded Streets". [Pig (song)]

==> distributed

Mello Yello is a highly-caffeinated, citrus-flavored soft drink produced and distributed by The Coca-Cola Company which was introduced on March 1, 1979 to compete with PepsiCo's Mountain Dew. [Mello Yello]
Podocarpus is a genus of conifers, the most numerous and widely distributed of the podocarp family, Podocarpaceae. [Podocarpus]
Spring and Fall is the nineteenth studio album by Australian folk rock singer-songwriter Paul Kelly which was issued in October 2012 on his own label, Gawd Aggie and distributed via Universal Music. [Spring and Fall (album)]
Ubuntu GNOME is a Linux distribution and distributed as free and open source software. [Ubuntu GNOME]
Joel Carl Hunter, is the senior pastor of Northland, A Church Distributed, a congregation of 20,000 that worships at three sites in Central Florida and at more than 1,000 sites worldwide via interactive webcast, iPhone, and Facebook. [Joel Hunter]

==> for

Elwyn Aubrey Walters was an Australian rugby league player for the South Sydney Rabbitohs and Eastern Suburbs clubs and for the Australian national side. [Elwyn Walters]
The New York Military Affairs Symposium, is an independent, not for profit educational body dedicated to the preservation and furthering of military history in the city of New York. [New York Military Affairs Symposium]
The Heinkel He 59 was a German biplane designed in 1930 resulting from a requirement for a torpedo bomber and reconnaissance aircraft able to operate with equal facility on wheeled landing gear or twin-floats. [Heinkel He 59]
Jason Zada is an American film director, music video director, screenwriter and digital marketeer, best known for "Elf Yourself", an interactive viral holiday season campaign for OfficeMax, and for "Take This Lollipop", an interactive horror short film created to raise awareness of the danger of placing too much personal information online. [Jason Zada]
William Longespée, 3rd Earl of Salisbury was an English noble, primarily remembered for his command of the English forces at the Battle of Damme and for remaining loyal to his half-brother, King John. [William Longesp&#233;e, 3rd Earl of Salisbury]

==> large

USNS "Charlton" is one of Military Sealift Command's nineteen Large, Medium-Speed Roll-on/Roll-off Ships and is part of the 33 ships in the Prepositioning Program. [USNS Charlton (T-AKR-314)]
Oil shale in Serbia is a large, but undeveloped energy resource. [Oil shale in Serbia]
Chunchucmil was once a large, sprawling pre-Columbian Maya city located in the western part of what is now the state of Yucatán, Mexico. [Chunchucmil]
USNS "Sisler" is one of Military Sealift Command's nineteen Large, Medium-Speed Roll-on/Roll-off Ships and is part of the 33 ships in the Prepositioning Program. [USNS Sisler (T-AKR-311)]
Oil shale in Belarus is a large, but undeveloped energy resource. [Oil shale in Belarus]

==> up

Luka Yovetich is an American actor and comedian, best known for co-starring in the NBC sitcoms "Best Friends Forever" and "Up All Night". [Luka Jones]
The Stars and Stripes Stakes is a Grade III flat horse race in the United States for thoroughbred horses aged three years and up. [Stars and Stripes Stakes]
"40 Day Dream"/"Geez Louise" is a 7" vinyl single released in the UK to succeed the album "Up from Below" by Edward Sharpe and the Magnetic Zeros. [40 Day Dream/Geez Louise]
Charles Leiper Grigg was the inventor of "Bib-Label Lithiated Lemon-Lime" soda, better known by its later name, 7 Up. [Charles Leiper Grigg]
Brassica hilarionis is a hairless perennial up to 1 m high with a basal rosette of roundish, fleshy, flat-stalked leaves, upper leaves stalkless and stem-clasping. [Brassica hilarionis]

**Comment by shu98** [comment]
==> red

>The beetroot is the taproot portion of the beet plant, usually known in North America as the beet, also table beet, garden beet, or red or golden beet. [Beetroot]
I think whoami is correct now. It returns [u'taproot portion', u'beet portion', u'table portion', u'portion', u'plant portion', u'beet plant portion']

> In CRT or computer terminology, a triad is a group of three phosphor dots coloured red, green, and blue on the inside of the CRT display of a computer monitor or television set. [Triad (computers)]
Returns 'coloured red group' but should not. 

> Ulmus 'Coolshade' is an American hybrid cultivar cloned from a crossing of the Slippery, or Red, Elm "Ulmus rubra" and the Siberian Elm "Ulmus pumila" at the Sarcoxie Nurseries, Sarcoxie, Missouri, in 1946. [Ulmus 'Coolshade']
I think whoami is correct now. It returns [u'hybrid cultivar', u'cultivar', u'american cultivar'].

> Upsdell red is a deep medium red, similar to Fire engine red. [Upsdell red]
Thorstein Eiriksson was the third and youngest son of Eiríkr the Red and brother of Leif Ericson. [Thorstein Eiriksson]
Whoami raises "Subject is not a noun" error.

**Comment by shu98** [comment]
Updated list of sentences that belong under this issue: "Remove non-noun definitions" 

==> blue

Gene Deer is an American blues, rock, and country musician/singer/songwriter based out of Indianapolis, Indiana. [Gene Deer]
Rick Bryant is a New Zealand blues and rock singer/songwriter. [Rick Bryant]
Calvin Leavy was an African American soul blues and electric blues singer and guitarist. [Calvin Leavy]
The West Coast blues is a type of blues influenced by jazz and jump blues, with strong piano-dominated sounds and jazzy guitar solos, which originated from Texas blues players who relocated to California in the 1940s. [West Coast blues]

==> red 

In CRT or computer terminology, a triad is a group of three phosphor dots coloured red, green, and blue on the inside of the CRT display of a computer monitor or television set. [Triad (computers)]

==> before

 "Friends" is a song by Danish singer-songwriter Aura Dione from her second studio album, "Before the Dinosaurs". [Friends (Aura Dione song)]

==> distributed 

 Ubuntu GNOME is a Linux distribution and distributed as free and open source software. [Ubuntu GNOME]

==> for 

None

==> large 

USNS "Charlton" is one of Military Sealift Command's nineteen Large, Medium-Speed Roll-on/Roll-off Ships and is part of the 33 ships in the Prepositioning Program. [USNS Charlton (T-AKR-314)]
USNS "Sisler" is one of Military Sealift Command's nineteen Large, Medium-Speed Roll-on/Roll-off Ships and is part of the 33 ships in the Prepositioning Program. [USNS Sisler (T-AKR-311)]

==> up

None

**Comment by shu98** [comment]
As a summary, most of these issues are all caused by bad spaCy parsing, and I am not sure if whoami is supposed to account for that or if we should just let it be.
